spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: service-registry-service
  client:
    register-with-eureka: false
    fetch-registry: false

server:
    port: 8761
