version: "3.7"
services:
  darkmode-service:
    image: gitlab.lrz.de:5005/ase23-seehamer-see/onlineide/dark-mode/darkmode
    restart: on-failure
    ports: 
      - 8083:8083
  compiler-service:
    image: gitlab.lrz.de:5005/ase23-seehamer-see/onlineide/compiler
    restart: on-failure
    ports:
      - 8082:8082  
  project-service:
    image: gitlab.lrz.de:5005/ase23-seehamer-see/onlineide/project
    restart: on-failure
    ports:
      - 8081:8081
  frontend-service:
    image: gitlab.lrz.de:5005/ase23-seehamer-see/onlineide/frontend_service
    restart: on-failure
    ports:
      - 8080:8080
  api-gateway-service:
    image: gitlab.lrz.de:5005/ase23-seehamer-see/onlineide/api-gateway
    restart: on-failure
    ports:
      - 8084:8084
  service-registry-service:
    image: gitlab.lrz.de:5005/ase23-seehamer-see/onlineide/service-registry
    restart: on-failure
    ports:
      - 8761:8761
