version: "3.7"
services:
  dark-mode-service:
    container_name: dark-mode-service
    build:
      context: ./dark-mode/darkmode
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8083:8083
    networks:
      - springapipostgres-net

  projectservicedb:
    image: "postgres:latest"
    container_name: projectservicedb
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: project-db

  project-service:
    container_name: project-service
    build:
      context: ./project
      dockerfile: Dockerfile
    #restart: on-failure
    image: project-service:latest
    ports:
      - 8081:8081
    networks:
      - springapipostgres-net
    environment:
      - JDBC_URL=jdbc:postgresql://projectservicedb:5432/project-db?user=admin&password=test

  compiler-service:
    container_name: compiler-service
    build:
      context: ./compiler
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8082:8082
    networks:
      - springapipostgres-net
    # depends_on:
    #   - project-service

  frontend-service:
    container_name: frontend_service
    build:
      context: ./frontend_service
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - springapipostgres-net
    depends_on:
      - project-service
      - dark-mode-service
      - compiler-service

  api-gateway-service:
    container_name: api_gateway_service
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8084:8084
    networks:
      - springapipostgres-net
    # depends_on:
    #   - project-service
    #   - dark-mode-service
    #   - compiler-service

  service-registry-service:
    container_name: service_registry_service
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8761:8761
    networks:
      - springapipostgres-net
    # depends_on:
    #   - project-service
    #   - dark-mode-service
    #   - compiler-service
  
networks:
  springapipostgres-net: