spring:
  application:
    name: api_gateway-service
  oauth2:
    client:
      clientId: clientID
      clientSecret: clientSecret
      accessTokenUri: https://gitlab.lrz.de/oauth/token
      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
      scope:
        - read_user
        - api
    resource:
      userInfoUri: https://gitlab.lrz.de/api/v4/user
  cloud:
    gateway:
      routes:
        - id: frontend-service
          uri: lb://frontend-service
          predicates:
            - Path=/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/**
        - id: compiler-service
          uri: lb://compiler-service
          predicates:
            - Path=/compile
        - id: dark-mode
          uri: lb://dark-mode
          predicates:
            - Path=/dark-mode/toggle
        - id: service-registry
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/dashboard
          filters:
            - SetPath=/
        - id: service-registry-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
server:
  port: ${PORT:8000}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
