spring:
  security:
    oauth2:
      client:
        provider:
          gitlab:
            authorization-uri: https://gitlab.lrz.de/oauth/authorize
            token-uri: https://gitlab.lrz.de/oauth/token
            user-info-uri: https://gitlab.lrz.de/api/v4/user
            user-name-attribute: username
        registration:
          gitlab:
            provider: gitlab
            redirect-uri: http://localhost:8080/login/oauth2/code/gitlab
            authorization-grant-type: authorization_code
            client-id: 3c320a9378bae7dd876289b05524903b5936ca7b5600d67a9021a409eeda2a36
            client-secret: gloas-ba57805815c00aef91e93a8750f40e23d3f645b3591bcc34584f7201d5f6f67a
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/**
        - id: compiler-service
          uri: lb://compiler-service
          predicates:
            - Path=/compilecd
        - id: dark-mode
          uri: lb://dark-mode
          predicates:
            - Path=/dark-mode/toggle
        - id: service-registry
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/dashboard
          filters:
            - SetPath=/
        - id: service-registry-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
