spring:
  security:
    oauth2:
      client:
        provider:
          gitlab:
            authorization-uri: https://gitlab.lrz.de/oauth/authorize
            token-uri: https://gitlab.lrz.de/oauth/token
            user-info-uri: https://gitlab.lrz.de/api/v4/user
            user-name-attribute: username
        registration:
          gitlab:
            provider: gitlab
            redirect-uri: http://localhost:8080/login/oauth2/code/gitlab
            authorization-grant-type: authorization_code
            client-id: 8910d32ed7ac4b90e31fb6285b6da16daf77a6e8841fe1a62ffff46d121617aa
            client-secret: gloas-cb0e46bc2cd592844b616ba1e5cafaf1eac1eedc553203ea0d19b7426a2b5462
  application:
    name: api-gateway

zuul:
  routes:
    project-service:
      path: /api/**
      serviceId: project-service
    compiler-service:
      path: /compile/**
      serviceId: compiler-service
    dark-mode:
      path: /dark-mode/**
      serviceId: dark-mode
    service-registry-static:
      path: /eureka/**
      url: http://localhost:8761
    service-registry:
      path: /eureka/dashboard/**
      url: http://localhost:8761

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka

