spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/**
        - id: compiler-service
          uri: lb://compiler-service
          predicates:
            - Path=/compile
        - id: dark-mode
          uri: lb://dark-mode
          predicates:
            - Path=/dark-mode/toggle
        - id: service-registry
          uri: http://service-registry-service:8761
          predicates:
            - Path=/eureka/dashboard
          filters:
            - SetPath=/
        - id: service-registry-static
          uri: http://service-registry-service:8761
          predicates:
            - Path=/eureka/**
eureka:
  client:
    service-url:
        defaultZone: http://service-registry-service:8761/eureka