# spring.datasource.url=jdbc:postgresql://localhost:5432/project-db?user=admin&password=test
# spring.datasource.username=admin
# spring.datasource.password=test
# spring.datasource.name=project-db

spring:
  application:
    name: project-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://projectservicedb:5432/project-db?user=admin&password=test
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:test}
    name: ${POSTGRES_DB:project-db}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        #jdbc.lob.non_contextual_creation: true
    #generate-ddl: true
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka