spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/project-service
    username: admin
    password: test
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          gitlab:
            authorization-uri: https://gitlab.lrz.de/oauth/authorize
            token-uri: https://gitlab.lrz.de/oauth/token
            user-info-uri: https://gitlab.lrz.de/api/v4/user
            user-name-attribute: username
        registration:
          gitlab:
            provider: gitlab
            redirect-uri-template: "http://localhost:4200/projects"
            client-id: 3c320a9378bae7dd876289b05524903b5936ca7b5600d67a9021a409eeda2a36
            client-secret: gloas-186ddd1cb93d0729f6a3e24843675ace5de758541c3bf766f06c4531d62945c6
            scope: read_user,api
            authorization-grant-type: authorization_code

server:
  port: 8081
