spring:
  application:
    name: backend-service
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://postgresdb:5432/project-db?user=admin&password=test}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:test}
    name: ${POSTGRES_DB:project-db}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        #jdbc.lob.non_contextual_creation: true
    #generate-ddl: true
server:
  port: ${PORT:8081}
database.port: ${DB_PORT:5432}